#!/bin/sh
#
# aarons_foo_mod
#
# Created by Aaron DeForest
#

# Make sure we are in the framework.
# This will halt execution if there is no is_debug function.
af_is_valid_function af_is_debug


afm_start_it1()
{
    echo "we are running afm_start_it1.  Now it is finished.  $1" 1>&2
    echo "here is a property from the property file : "`af_get_property_value aarons_value`
    exit 0
}

afm_start_it2()
{
    if [ -z "$1" ] ; then
	echo "we are running afm_start_it2, but start it2 has a problem!"
	return 2
    else
	echo "start_it2 has the parameter of : $1!!"
	return 0
    fi
}

afm_start_it3()
{
    echo "we are running afm_start_it3.  Start it3 is the last function."
    exit 0
}
